-- UI_TYPE
INSERT INTO PUBLIC.UI_TYPE (ID,NAME,"ELEMENT",EXPRESSION) VALUES (
1351,'Normales Textfeld','TEXT_FIELD','');
INSERT INTO PUBLIC.UI_TYPE (ID,NAME,"ELEMENT",EXPRESSION) VALUES (
1352,'Normaler Zahlenspinner','INTEGER_SPINNER','');
INSERT INTO PUBLIC.UI_TYPE (ID,NAME,"ELEMENT",EXPRESSION) VALUES (
1353,'Tankauswahl','SEARCHABLE_COMBOBOX','ENTITY=CONTAINER');

-- MEASURE_TYPE
INSERT INTO PUBLIC.MEASURE_TYPE (ID,NAME,FILLING_EFFECT,ORDER_NUMBER,COLOR,ICON,ICON_CONTENT_TYPE,DELETED_AT,PARENT_ID) VALUES (
1251,'Lese','REFILL',101,'',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.MEASURE_TYPE (ID,NAME,FILLING_EFFECT,ORDER_NUMBER,COLOR,ICON,ICON_CONTENT_TYPE,DELETED_AT,PARENT_ID) VALUES (
1255,'Traubenzukauf','REFILL',101,'',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.MEASURE_TYPE (ID,NAME,FILLING_EFFECT,ORDER_NUMBER,COLOR,ICON,ICON_CONTENT_TYPE,DELETED_AT,PARENT_ID) VALUES (
1252,'Schwefelung','NO_EFFECT',102,'',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.MEASURE_TYPE (ID,NAME,FILLING_EFFECT,ORDER_NUMBER,COLOR,ICON,ICON_CONTENT_TYPE,DELETED_AT,PARENT_ID) VALUES (
1253,'Vorfiltration','TRANSFILL',103,'',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.MEASURE_TYPE (ID,NAME,FILLING_EFFECT,ORDER_NUMBER,COLOR,ICON,ICON_CONTENT_TYPE,DELETED_AT,PARENT_ID) VALUES (
1254,'Flaschenfüllung','BOTTLED',104,'',NULL,NULL,NULL,NULL);

-- MEASURE_PROPERTY_TYPE
INSERT INTO PUBLIC.MEASURE_PROPERTY_TYPE (ID,"TYPE",ORDER_NUMBER,UI_TYPE_ID) VALUES (
1,'Von Tank',1,1353);
INSERT INTO PUBLIC.MEASURE_PROPERTY_TYPE (ID,"TYPE",ORDER_NUMBER,UI_TYPE_ID) VALUES (
2,'Zu Tank',2,1353);


-- POSSIBLE_P_TYPES_FOR_M_TYPES
INSERT INTO PUBLIC.POSSIBLE_P_TYPES_FOR_M_TYPES (ID,MEASURE_TYPE_ID,MEASURE_PROPERTY_TYPE_ID) VALUES (
1403,1253,1303);
INSERT INTO PUBLIC.POSSIBLE_P_TYPES_FOR_M_TYPES (ID,MEASURE_TYPE_ID,MEASURE_PROPERTY_TYPE_ID) VALUES (
1404,1253,1304);
