INSERT INTO PUBLIC.CONTAINER_TYPE (ID,NAME,DELETED_AT,COLOR,ORDER_NUMBER,ICON,ICON_CONTENT_TYPE) VALUES (
1101,'Holz',NULL,'',NULL,NULL,NULL);
INSERT INTO PUBLIC.CONTAINER_TYPE (ID,NAME,DELETED_AT,COLOR,ORDER_NUMBER,ICON,ICON_CONTENT_TYPE) VALUES (
1102,'Edelstahl',NULL,'',NULL,NULL,NULL);
INSERT INTO PUBLIC.CONTAINER_TYPE (ID,NAME,DELETED_AT,COLOR,ORDER_NUMBER,ICON,ICON_CONTENT_TYPE) VALUES (
1103,'Kunststoff',NULL,'',NULL,NULL,NULL);
