INSERT INTO PUBLIC.CONTAINER (ID,NAME,IS_ALWAYS_FULL,CURRENT_AMOUNT_OF_CONTENT,CAPACITY,COLOR,ORDER_NUMBER,ICON,ICON_CONTENT_TYPE,DELETED_AT,LOCATION_ID,CONTAINER_TYPE_ID) VALUES (
1151,'Fass 1',false,0,10000,'',1,NULL,NULL,NULL,1052,1103);
INSERT INTO PUBLIC.CONTAINER (ID,NAME,IS_ALWAYS_FULL,CURRENT_AMOUNT_OF_CONTENT,CAPACITY,COLOR,ORDER_NUMBER,ICON,ICON_CONTENT_TYPE,DELETED_AT,LOCATION_ID,CONTAINER_TYPE_ID) VALUES (
1152,'kleines Fass 1',false,0,300,'',2,NULL,NULL,NULL,1051,1102);
