INSERT INTO PUBLIC.JHI_USER_AUTHORITY (USER_ID,AUTHORITY_NAME) VALUES (
1,'ROLE_ADMIN');
INSERT INTO PUBLIC.JHI_USER_AUTHORITY (USER_ID,AUTHORITY_NAME) VALUES (
1,'ROLE_USER');
INSERT INTO PUBLIC.JHI_USER_AUTHORITY (USER_ID,AUTHORITY_NAME) VALUES (
3,'ROLE_ADMIN');
INSERT INTO PUBLIC.JHI_USER_AUTHORITY (USER_ID,AUTHORITY_NAME) VALUES (
3,'ROLE_USER');
INSERT INTO PUBLIC.JHI_USER_AUTHORITY (USER_ID,AUTHORITY_NAME) VALUES (
4,'ROLE_USER');
