INSERT INTO PUBLIC.LOCATION (ID,NAME,COLOR,ICON,ICON_CONTENT_TYPE,ORDER_NUMBER,DELETED_AT) VALUES (
1051,'Droß','',NULL,NULL,1,NULL);
INSERT INTO PUBLIC.LOCATION (ID,NAME,COLOR,ICON,ICON_CONTENT_TYPE,ORDER_NUMBER,DELETED_AT) VALUES (
1052,'Stratzing','',NULL,NULL,2,NULL);
