INSERT INTO PUBLIC.MEASURE_TYPE (ID,NAME,FILLING_EFFECT,ORDER_NUMBER,COLOR,ICON,ICON_CONTENT_TYPE,DELETED_AT,PARENT_ID) VALUES (
1251,'Mostfüllung','REFILL',101,'',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.MEASURE_TYPE (ID,NAME,FILLING_EFFECT,ORDER_NUMBER,COLOR,ICON,ICON_CONTENT_TYPE,DELETED_AT,PARENT_ID) VALUES (
1252,'Schwefelung','NO_EFFECT',102,'',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.MEASURE_TYPE (ID,NAME,FILLING_EFFECT,ORDER_NUMBER,COLOR,ICON,ICON_CONTENT_TYPE,DELETED_AT,PARENT_ID) VALUES (
1253,'Vorfiltration','TRANSFILL',103,'',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.MEASURE_TYPE (ID,NAME,FILLING_EFFECT,ORDER_NUMBER,COLOR,ICON,ICON_CONTENT_TYPE,DELETED_AT,PARENT_ID) VALUES (
1254,'Flaschenfüllung','BOTTLED',104,'',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.MEASURE_TYPE (ID,NAME,FILLING_EFFECT,ORDER_NUMBER,COLOR,ICON,ICON_CONTENT_TYPE,DELETED_AT,PARENT_ID) VALUES (
1255,'Traubenzukauf','REFILL',101,'',NULL,NULL,NULL,NULL);
