INSERT INTO PUBLIC.MEASURE_PROPERTY_TYPE (ID,"TYPE",ORDER_NUMBER,UI_TYPE_ID) VALUES (
1201,'Rebe',102,1351);
INSERT INTO PUBLIC.MEASURE_PROPERTY_TYPE (ID,"TYPE",ORDER_NUMBER,UI_TYPE_ID) VALUES (
1202,'Zulieferer',103,1351);
INSERT INTO PUBLIC.MEASURE_PROPERTY_TYPE (ID,"TYPE",ORDER_NUMBER,UI_TYPE_ID) VALUES (
1301,'Weinsorte',101,1351);
INSERT INTO PUBLIC.MEASURE_PROPERTY_TYPE (ID,"TYPE",ORDER_NUMBER,UI_TYPE_ID) VALUES (
1302,'Menge in g/L',201,1352);
INSERT INTO PUBLIC.MEASURE_PROPERTY_TYPE (ID,"TYPE",ORDER_NUMBER,UI_TYPE_ID) VALUES (
1303,'Von Tank',1,1353);
INSERT INTO PUBLIC.MEASURE_PROPERTY_TYPE (ID,"TYPE",ORDER_NUMBER,UI_TYPE_ID) VALUES (
1304,'Zu Tank',2,1353);
INSERT INTO PUBLIC.MEASURE_PROPERTY_TYPE (ID,"TYPE",ORDER_NUMBER,UI_TYPE_ID) VALUES (
1305,'Weinbezeichnung',401,1351);
