INSERT INTO PUBLIC.POSSIBLE_P_TYPES_FOR_M_TYPES (ID,MEASURE_TYPE_ID,MEASURE_PROPERTY_TYPE_ID) VALUES (
1251,1251,1201);
INSERT INTO PUBLIC.POSSIBLE_P_TYPES_FOR_M_TYPES (ID,MEASURE_TYPE_ID,MEASURE_PROPERTY_TYPE_ID) VALUES (
1252,1255,1202);
INSERT INTO PUBLIC.POSSIBLE_P_TYPES_FOR_M_TYPES (ID,MEASURE_TYPE_ID,MEASURE_PROPERTY_TYPE_ID) VALUES (
1253,1255,1301);
INSERT INTO PUBLIC.POSSIBLE_P_TYPES_FOR_M_TYPES (ID,MEASURE_TYPE_ID,MEASURE_PROPERTY_TYPE_ID) VALUES (
1401,1251,1301);
INSERT INTO PUBLIC.POSSIBLE_P_TYPES_FOR_M_TYPES (ID,MEASURE_TYPE_ID,MEASURE_PROPERTY_TYPE_ID) VALUES (
1402,1252,1302);
INSERT INTO PUBLIC.POSSIBLE_P_TYPES_FOR_M_TYPES (ID,MEASURE_TYPE_ID,MEASURE_PROPERTY_TYPE_ID) VALUES (
1403,1253,1303);
INSERT INTO PUBLIC.POSSIBLE_P_TYPES_FOR_M_TYPES (ID,MEASURE_TYPE_ID,MEASURE_PROPERTY_TYPE_ID) VALUES (
1404,1253,1304);
INSERT INTO PUBLIC.POSSIBLE_P_TYPES_FOR_M_TYPES (ID,MEASURE_TYPE_ID,MEASURE_PROPERTY_TYPE_ID) VALUES (
1405,1254,1305);
