INSERT INTO PUBLIC.UI_TYPE (ID,NAME,"ELEMENT",EXPRESSION) VALUES (
1351,'Normales Textfeld','TEXT_FIELD','');
INSERT INTO PUBLIC.UI_TYPE (ID,NAME,"ELEMENT",EXPRESSION) VALUES (
1352,'Normaler Zahlenspinner','INTEGER_SPINNER','');
INSERT INTO PUBLIC.UI_TYPE (ID,NAME,"ELEMENT",EXPRESSION) VALUES (
1353,'Tankauswahl','SEARCHABLE_COMBOBOX','ENTITY=CONTAINER');
